### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [shssoichiro/avsser#2]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by shssoichiro** [comment]
I will say I wish that the `hex` crate could deserialize into a fixed-size array, like `rustc-serialize` could. I found a better way to do it in this crate (because the hex strings were UUIDs), but it would still be a good functionality to have.

**Comment by dtolnay** [comment]
Thanks, I reported this in https://github.com/KokaKiwi/rust-hex/issues/10.
